branches:
  only:
  - master
language: ruby
rvm:
- 1.9.3
before_script:
- git config --global user.name "Hoat Le"
- git config --global user.email "hoatlevan@gmail.com"
- export REPO_URL="https://$GH_TOKEN@github.com/$GH_REPO.git"
- bundle exec rake setup_github_pages[$REPO_URL]
- git checkout -- _config.yml
script: bundle exec rake generate
after_script:
- bundle exec rake deploy
env:
  global:
  - GH_REPO="hoatle/blog.hoatle.info"
  - secure: afk+pGHhsNqdhJ/rfhqaAqLjF8wlbrn2APdVkPBje0K/i0t/ifokQM6B9fm1XTIPwNHpVU5q79iL93AOYPmHXfoWe8nY8LwQINZrDc/+N1j6H3sQl1N5G1z75IXKGHKat48U4Dn12TioE/TqflkDzDmpVTVLlf40sVIilVly5f8=
